"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useInView } from "framer-motion";
import { ArrowRight, Bot, BrainCircuit, CalendarDays, Check, ChevronDown, Cpu, Github, Instagram, Layers3, Linkedin, Mail, Menu, MessageSquareText, PhoneCall, Play, ShieldCheck, Sparkles, Workflow, X, Zap } from "lucide-react";

const rise = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0 } };
const services = [
  [PhoneCall, "AI Lead Qualification & Response", "Instantly capture, qualify, and respond to every lead. Faster responses, higher conversions, no missed leads."],
  [MessageSquareText, "AI Client Onboarding", "Automate onboarding from form submission to client welcome. Better client experience, less manual work, faster onboarding."],
  [Workflow, "AI Sales Follow-up", "Automatically follow up with leads using AI-generated emails and reminders. More booked meetings, higher conversion rates, consistent follow-ups."],
  [Layers3, "AI Business Insights & Reporting", "Generate daily and weekly reports with actionable insights. Better decisions, saved time, identify opportunities faster."]
];
const projects = [
  ["AI Lead Qualification & Response", "Instantly captures, qualifies, scores, and responds to every lead automatically.", "", ["n8n", "OpenAI", "Gmail", "CRM"]],
  ["AI Client Onboarding", "Automates the complete onboarding process from signed client to project kickoff.", "", ["n8n", "Google Sheets", "Forms", "CRM"]],
  ["AI Sales Follow-up", "AI automatically follows up with leads using personalized emails and reminders.", "", ["OpenAI", "Gmail", "n8n", "WhatsApp"]],
  ["AI Business Insights & Reporting", "AI analyzes business data and delivers actionable daily or weekly reports.", "", ["Google Sheets", "OpenAI", "Dashboards", "APIs"]]
];
const tech = ["OpenAI", "Gemini", "Claude", "n8n", "Supabase", "Pinecone", "Next.js", "React", "Node.js", "Python", "Docker", "PostgreSQL", "REST APIs", "Webhooks", "Tailwind"];
const faqs = [["How long does it take to build an automation?", "Most projects are delivered within 1–3 weeks depending on complexity and integrations."], ["Will it work with my existing software?", "Yes. We build integrations with CRMs, Google Workspace, Microsoft 365, Slack, WhatsApp, APIs, and many other business tools."], ["What if my business process is unique?", "Every automation is custom-built around your existing workflow. We don't force your business to adapt to generic software."], ["How much maintenance is required?", "Very little. We monitor deployments, provide support, and make improvements as your business grows."], ["Is my business data secure?", "Yes. We follow secure integration practices and only access the systems required to deliver your automation."], ["Can AI make mistakes?", "AI assists with repetitive tasks, but workflows can include validation, approvals, and human review wherever needed."], ["How do we get started?", "We begin with a discovery call to understand your business, identify bottlenecks, and recommend the highest-impact automation opportunities."], ["What kind of businesses do you work with?", "We primarily help service businesses, agencies, consultants, and growing companies eliminate repetitive work and improve operations."]];

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} variants={rise} initial="hidden" whileInView="show" viewport={{ once: true, amount: .18 }} transition={{ duration: .6, ease: "easeOut" }}>{children}</motion.div>; }
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy?: string }) { return <Reveal className="section-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="lede">{copy}</p>}</Reveal>; }
function ProjectVideo({ src }: { src?: string }) { if (!src) return <div className="video-fallback"><Cpu/><span>Demo thumbnail</span></div>; const ref = useRef<HTMLVideoElement>(null); const visible = useInView(ref, { amount: .45 }); useEffect(() => { const v = ref.current; if (!v) return; visible ? v.play().catch(() => {}) : v.pause(); }, [visible]); return <video ref={ref} muted loop playsInline preload="metadata" aria-label="Project demonstration video"><source src={`/videos/${src}`} type="video/mp4" /></video>; }

export default function AgencySite() {
  const [open, setOpen] = useState<number | null>(null); const [mobile, setMobile] = useState(false);
  return <main>
    <div className="ambient ambient-one" /><div className="ambient ambient-two" /><div className="grain" />
    <nav aria-label="Main navigation"><a className="brand" href="#top"><span>N</span>NEXUS</a><div className={mobile ? "nav-links mobile-open" : "nav-links"}><a href="#services" onClick={() => setMobile(false)}>Capabilities</a><a href="#work" onClick={() => setMobile(false)}>Work</a><a href="#process" onClick={() => setMobile(false)}>Process</a><a href="#founder" onClick={() => setMobile(false)}>About</a><a className="nav-cta" href="#contact" onClick={() => setMobile(false)}>Let’s talk <ArrowRight size={15}/></a></div><button className="menu" aria-label="Toggle navigation" onClick={() => setMobile(!mobile)}>{mobile ? <X/> : <Menu/>}</button></nav>
    <section id="top" className="hero"><Reveal className="hero-copy"><div className="pill"><span /> AUTOMATION SYSTEMS FOR AMBITIOUS TEAMS</div><h1>Stop manual work from<br/>slowing your growth.<br/><em>Scale operations without hiring more.</em></h1><p>We build self-running systems that qualify leads, book meetings, and resolve repeat tasks so your team can focus on growth instead of grind.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Start with a free strategy call <ArrowRight size={17}/></a><a className="button button-ghost" href="#work"><Play size={14} fill="currentColor"/> See live system demos</a></div><div className="trust"><div className="avatars"><i>J</i><i>M</i><i>S</i></div><span>Trusted by operators who refuse to<br/>let busywork set the pace.</span></div></Reveal><Reveal className="ai-stage"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="ai-core"><div className="core-ring"/><BrainCircuit size={64}/><span>ACTIVE</span></div><div className="node node-one"><Bot/><div><b>Lead agent</b><small>Qualifying now</small></div><Check size={15}/></div><div className="node node-two"><CalendarDays/><div><b>Booking agent</b><small>3 meetings set</small></div></div><div className="node node-three"><Zap/><div><b>Workflow live</b><small>12 tasks completed</small></div></div><div className="data-line line-one"/><div className="data-line line-two"/></Reveal></section>
    <section className="problems"><Reveal><div className="problem-head"><p className="eyebrow">THE COST OF THE STATUS QUO</p><h2>Manual work quietly<br/>taxes every <em>ambition.</em></h2></div></Reveal><div className="transformation"><Reveal className="pain-list">{["Too much manual work", "Leads get missed", "Teams repeat the same tasks", "Slow customer support", "High operational costs"].map(x => <div key={x}><X size={16}/>{x}</div>)}</Reveal><Reveal className="transform-arrow"><ArrowRight /></Reveal><Reveal className="gain-list">{["AI employees", "Automated workflows", "Faster responses", "Lower costs", "More room to grow"].map(x => <div key={x}><Check size={16}/>{x}</div>)}</Reveal></div></section>
    <section id="services"><SectionTitle eyebrow="WHAT WE BUILD" title={<>Capability that compounds.<br/><em>Systems that perform.</em></>} copy="Every solution begins with a sharp business outcome, then becomes a dependable system your team can build around."/><div className="service-grid">{services.map(([Icon, title, description], i) => <Reveal key={String(title)}><motion.article className="service-card" whileHover={{ y: -8, rotateX: 2, rotateY: i % 2 ? -2 : 2 }} transition={{ type: "spring", stiffness: 250, damping: 18 }}><div className="service-icon"><Icon size={21}/></div><h3>{String(title)}</h3><p>{String(description)}</p><span className="learn">Explore capability <ArrowRight size={15}/></span></motion.article></Reveal>)}</div></section>
    <section id="work"><SectionTitle eyebrow="SELECTED SYSTEMS" title={<>Not prototypes. <em>Proof.</em></>} copy="A glimpse at the systems we create when technical excellence meets commercial clarity."/><div className="project-grid">{projects.map(([title, description, video, tags]) => <Reveal key={String(title)}><motion.article className="project-card" whileHover={{ y: -8 }}><div className="video-wrap"><ProjectVideo src={String(video)} /><span className="live-dot">LIVE DEMO</span></div><div className="project-info"><h3>{String(title)}</h3><p>{String(description)}</p><div className="project-tags">{(tags as string[]).map(tag => <span key={tag}>{tag}</span>)}</div><a className="button button-ghost" href="#contact">Watch Demo</a></div></motion.article></Reveal>)}</div></section>
    <section className="tech-section"><SectionTitle eyebrow="THE RIGHT FOUNDATION" title={<>Built on the tools<br/>that <em>move business.</em></>} /><div className="tech-cloud">{tech.map((t, i) => <motion.div key={t} className="tech-card" animate={{ y: [0, i % 2 ? -9 : 9, 0] }} transition={{ repeat: Infinity, duration: 3 + (i % 3), ease: "easeInOut", delay: i * .1 }}><span>{String(t).slice(0, 1)}</span>{t}</motion.div>)}</div></section>
    <section className="why"><SectionTitle eyebrow="WHY NEXUS" title={<>Designed to become your<br/><em>operating advantage.</em></>} /><div className="why-grid">{[["01", "Save hundreds of hours", "Give your team time back for the work only humans can do."], ["02", "Increase revenue", "Respond to opportunity at the speed buyers expect."], ["03", "Reduce costs", "Replace capacity constraints with intelligent, consistent execution."], ["04", "24/7 AI employees", "Keep the business moving beyond the limits of the workday."], ["05", "Custom built", "No off-the-shelf workflows forced onto your business."], ["06", "Scales with you", "A technical foundation that earns its place as you grow."]].map(([n,t,c]) => <Reveal key={n}><article className="why-card"><span>{n}</span><h3>{t}</h3><p>{c}</p></article></Reveal>)}</div></section>
    <section id="process" className="process"><SectionTitle eyebrow="HOW WE WORK" title={<>From friction to <em>flow.</em></>} copy="A focused, transparent process that keeps the business outcome in sight."/><div className="timeline">{["Discovery call", "Business analysis", "AI solution design", "Development", "Testing", "Deployment", "Ongoing support"].map((x,i) => <Reveal key={x}><div className="step"><span>0{i+1}</span><b>{x}</b>{i < 6 && <i/>}</div></Reveal>)}</div></section>
    <section id="founder" className="founder"><Reveal className="portrait"><div className="portrait-placeholder"><span>SD</span><p>SHIVAM DHOKANE<br/><small>FOUNDER / AI ARCHITECT</small></p></div></Reveal><Reveal className="founder-copy"><p className="eyebrow">MEET THE FOUNDER</p><h2>Built by a systems thinker<br/>with a bias for <em>action.</em></h2><p>Hi, I’m Shivam Dhokane, founder of Nexus Automation.</p><p>I help businesses eliminate repetitive work by designing intelligent automation systems that save time, improve customer experience, and create scalable operations.</p><p>Rather than selling software, I work with business owners to understand their processes, identify bottlenecks, and build AI systems that produce measurable business results.</p><p>My goal is simple: help businesses spend less time on manual work and more time growing.</p><div className="stats">{[["AI Automation Specialist", "Designing AI systems that eliminate repetitive business operations."], ["End-to-End Solutions", "From business analysis and workflow design to deployment and ongoing support."], ["Built for Business Growth", "Every automation is designed to save time, reduce costs, and help businesses scale."]].map(([n,l]) => <div key={n}><b>{n}</b><span>{l}</span></div>)}</div></Reveal></section>
    <section className="testimonials"><SectionTitle eyebrow="EXPECTED BUSINESS OUTCOMES" title="Expected Business Outcomes" copy="The results businesses can expect after implementing the right AI systems." /><div className="quote-grid">{[["Save Time Every Week", "Automate repetitive administrative work, reduce manual processes, and give your team more time to focus on high-value activities."], ["Respond Faster", "Capture, qualify, and respond to customer inquiries automatically so opportunities are never missed."], ["Scale Without Hiring", "Build AI systems that handle repetitive operations consistently, allowing your business to grow without increasing operational overhead."]].map(([title, description]) => <Reveal key={title}><blockquote><div>OUTCOME</div><h3>{title}</h3><p>{description}</p></blockquote></Reveal>)}</div><p className="testimonial-note">Every business is different. Results depend on your existing processes, systems, and implementation.</p></section>
    <section className="faq"><SectionTitle eyebrow="FREQUENTLY ASKED" title={<>Good questions.<br/><em>Clear answers.</em></>} /><div className="accordion">{faqs.map(([q,a],i) => <div className={open===i ? "faq-item open" : "faq-item"} key={q}><button onClick={() => setOpen(open===i ? null:i)} aria-expanded={open===i}>{q}<ChevronDown size={19}/></button>{open===i && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }}>{a}</motion.p>}</div>)}</div></section>
    <section id="contact" className="contact"><Reveal><div className="contact-card"><div><p className="eyebrow">READY TO ELIMINATE REPETITIVE WORK?</p><h2>Ready to Eliminate<br/>Repetitive Work?</h2><p>Let's identify the biggest bottlenecks in your business and design AI systems that save time, reduce manual work, and help your business grow.</p><div className="contact-meta"><Mail size={16}/> hello@nexusautomation.ai</div><div className="contact-next"><p className="eyebrow">WHAT HAPPENS NEXT?</p><div><b>1. Discovery Call</b><p>We learn about your business, processes, and current challenges.</p></div><div><b>2. Automation Assessment</b><p>We identify repetitive tasks and the highest-impact automation opportunities.</p></div><div><b>3. Custom Solution</b><p>We design an AI automation system tailored to your business.</p></div><div><b>4. Deployment & Support</b><p>We build, test, deploy, and provide ongoing improvements as your business grows.</p></div></div></div><form onSubmit={e => e.preventDefault()}><label>Full Name<input required placeholder="Your full name"/></label><label>Business Email<input required type="email" placeholder="you@company.com"/></label><label>Company Name<input placeholder="Company name"/></label><label>What challenge are you trying to solve?<input placeholder="Describe the business challenge"/></label><label className="full">Tell us about your current process (optional)<textarea placeholder="Describe your current process or biggest bottleneck" rows={3}/></label><button className="button button-primary full">Book a Free Strategy Call <ArrowRight size={17}/></button><a className="button button-ghost full" href="#services">Explore Our Solutions</a><p className="contact-note">No sales pressure. Just a practical conversation about whether AI automation can genuinely improve your business.</p></form></div></Reveal></section>
    <footer className="site-footer"><a className="brand" href="#top"><span>N</span>NEXUS</a><p>Intelligent systems for businesses<br/>that intend to lead.</p><div className="footer-links"><a href="#services">Capabilities</a><a href="#work">Work</a><a href="#contact">Contact</a></div><div className="socials"><a aria-label="LinkedIn" href="#"><Linkedin size={18}/></a><a aria-label="GitHub" href="#"><Github size={18}/></a><a aria-label="Instagram" href="#"><Instagram size={18}/></a></div><small>© 2026 NEXUS Automation. All rights reserved.</small></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "ProfessionalService", name: "NEXUS AI Automation", description: "Custom AI agents and automation systems for businesses." }) }} />
  </main>;
}
