"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useInView } from "framer-motion";
import { ArrowRight, Bot, BrainCircuit, CalendarDays, Check, ChevronDown, Cpu, Github, Instagram, Layers3, Linkedin, Mail, Menu, MessageSquareText, PhoneCall, Play, ShieldCheck, Sparkles, Workflow, X, Zap } from "lucide-react";

const rise = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0 } };
const services = [
  [PhoneCall, "AI Voice Agents", "Natural conversations that qualify, book, and support around the clock."], [MessageSquareText, "AI Chatbots", "On-brand assistants that turn every customer question into momentum."], [Workflow, "Workflow Automation", "Connected systems that remove manual handoffs and busywork."], [Layers3, "CRM Automation", "Pipelines that stay clean, current, and ready for action."], [Sparkles, "Lead Qualification", "Intent-aware scoring that puts the right leads in front of sales."], [MessageSquareText, "WhatsApp Automation", "Fast, personal customer journeys on the channel they already use."], [Mail, "Email Automation", "Timely follow-ups that feel handcrafted at scale."], [BrainCircuit, "Custom AI Systems", "Purpose-built intelligence for your highest-leverage operations."]
];
const projects = [
  ["Voice concierge", "An AI receptionist that answers, qualifies, and books appointments in real time.", "demo1.mp4", ["Voice AI", "CRM", "Calendar"]], ["Revenue engine", "A lead-response system that turns inbound intent into qualified conversations.", "demo2.mp4", ["OpenAI", "n8n", "HubSpot"]], ["Support command center", "A context-aware support layer that resolves requests before a ticket is created.", "demo3.mp4", ["RAG", "Supabase", "Slack"]], ["Ops autopilot", "A multi-step workflow agent built to move operational work without oversight.", "demo4.mp4", ["Agents", "APIs", "Postgres"]]
];
const tech = ["OpenAI", "Gemini", "Claude", "n8n", "Supabase", "Pinecone", "Next.js", "React", "Node.js", "Python", "Docker", "PostgreSQL", "REST APIs", "Webhooks", "Tailwind"];
const faqs = [["How quickly can we launch?", "Most focused systems launch in 2–4 weeks. Complex, multi-platform solutions are planned in clear phases so value arrives early."], ["Will it work with our existing tools?", "That is the point. We design around your CRM, inbox, calendar, databases and the tools your team already trusts."], ["Will it sound like a robot?", "No. We train flows, tone, escalation paths and knowledge sources around your brand, then rigorously test real-world edge cases."], ["What happens after deployment?", "We monitor performance, refine the system with live feedback and remain your technical partner as the business evolves."]];

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} variants={rise} initial="hidden" whileInView="show" viewport={{ once: true, amount: .18 }} transition={{ duration: .6, ease: "easeOut" }}>{children}</motion.div>; }
function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy?: string }) { return <Reveal className="section-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="lede">{copy}</p>}</Reveal>; }
function ProjectVideo({ src }: { src: string }) { const ref = useRef<HTMLVideoElement>(null); const visible = useInView(ref, { amount: .45 }); useEffect(() => { const v = ref.current; if (!v) return; visible ? v.play().catch(() => {}) : v.pause(); }, [visible]); return <video ref={ref} muted loop playsInline preload="metadata" aria-label="Project demonstration video"><source src={`/videos/${src}`} type="video/mp4" /></video>; }

export default function AgencySite() {
  const [open, setOpen] = useState<number | null>(null); const [mobile, setMobile] = useState(false);
  return <main>
    <div className="ambient ambient-one" /><div className="ambient ambient-two" /><div className="grain" />
    <nav aria-label="Main navigation"><a className="brand" href="#top"><span>N</span>NEXUS</a><div className={mobile ? "nav-links mobile-open" : "nav-links"}><a href="#services" onClick={() => setMobile(false)}>Capabilities</a><a href="#work" onClick={() => setMobile(false)}>Work</a><a href="#process" onClick={() => setMobile(false)}>Process</a><a href="#founder" onClick={() => setMobile(false)}>About</a><a className="nav-cta" href="#contact" onClick={() => setMobile(false)}>Let’s talk <ArrowRight size={15}/></a></div><button className="menu" aria-label="Toggle navigation" onClick={() => setMobile(!mobile)}>{mobile ? <X/> : <Menu/>}</button></nav>
    <section id="top" className="hero"><Reveal className="hero-copy"><div className="pill"><span /> AI SYSTEMS FOR AMBITIOUS TEAMS</div><h1>Build AI Employees<br/>That Work <em>24/7.</em></h1><p>We architect intelligent agents and automation systems that turn repetitive operations into your unfair advantage.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Book a free consultation <ArrowRight size={17}/></a><a className="button button-ghost" href="#work"><Play size={14} fill="currentColor"/> View live demos</a></div><div className="trust"><div className="avatars"><i>J</i><i>M</i><i>S</i></div><span>Trusted by operators who refuse to<br/>let busywork set the pace.</span></div></Reveal><Reveal className="ai-stage"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="ai-core"><div className="core-ring"/><BrainCircuit size={64}/><span>ACTIVE</span></div><div className="node node-one"><Bot/><div><b>Lead agent</b><small>Qualifying now</small></div><Check size={15}/></div><div className="node node-two"><CalendarDays/><div><b>Booking agent</b><small>3 meetings set</small></div></div><div className="node node-three"><Zap/><div><b>Workflow live</b><small>12 tasks completed</small></div></div><div className="data-line line-one"/><div className="data-line line-two"/></Reveal></section>
    <section className="problems"><Reveal><div className="problem-head"><p className="eyebrow">THE COST OF THE STATUS QUO</p><h2>Manual work quietly<br/>taxes every <em>ambition.</em></h2></div></Reveal><div className="transformation"><Reveal className="pain-list">{["Too much manual work", "Leads get missed", "Teams repeat the same tasks", "Slow customer support", "High operational costs"].map(x => <div key={x}><X size={16}/>{x}</div>)}</Reveal><Reveal className="transform-arrow"><ArrowRight /></Reveal><Reveal className="gain-list">{["AI employees", "Automated workflows", "Faster responses", "Lower costs", "More room to grow"].map(x => <div key={x}><Check size={16}/>{x}</div>)}</Reveal></div></section>
    <section id="services"><SectionTitle eyebrow="WHAT WE BUILD" title={<>Capability that compounds.<br/><em>Systems that perform.</em></>} copy="Every solution begins with a sharp business outcome, then becomes a dependable system your team can build around."/><div className="service-grid">{services.map(([Icon, title, description], i) => <Reveal key={String(title)}><motion.article className="service-card" whileHover={{ y: -8, rotateX: 2, rotateY: i % 2 ? -2 : 2 }} transition={{ type: "spring", stiffness: 250, damping: 18 }}><div className="service-icon"><Icon size={21}/></div><h3>{String(title)}</h3><p>{String(description)}</p><span className="learn">Explore capability <ArrowRight size={15}/></span></motion.article></Reveal>)}</div></section>
    <section id="work"><SectionTitle eyebrow="SELECTED SYSTEMS" title={<>Not prototypes. <em>Proof.</em></>} copy="A glimpse at the systems we create when technical excellence meets commercial clarity."/><div className="project-grid">{projects.map(([title, description, video, tags]) => <Reveal key={String(title)}><motion.article className="project-card" whileHover={{ y: -8 }}><div className="video-wrap"><ProjectVideo src={String(video)} /><div className="video-fallback"><Cpu/><span>Demo video</span></div><span className="live-dot">LIVE SYSTEM</span></div><div className="project-info"><h3>{String(title)}</h3><p>{String(description)}</p><div>{(tags as string[]).map(tag => <span key={tag}>{tag}</span>)}</div></div></motion.article></Reveal>)}</div></section>
    <section className="tech-section"><SectionTitle eyebrow="THE RIGHT FOUNDATION" title={<>Built on the tools<br/>that <em>move business.</em></>} /><div className="tech-cloud">{tech.map((t, i) => <motion.div key={t} className="tech-card" animate={{ y: [0, i % 2 ? -9 : 9, 0] }} transition={{ repeat: Infinity, duration: 3 + (i % 3), ease: "easeInOut", delay: i * .1 }}><span>{String(t).slice(0, 1)}</span>{t}</motion.div>)}</div></section>
    <section className="why"><SectionTitle eyebrow="WHY NEXUS" title={<>Designed to become your<br/><em>operating advantage.</em></>} /><div className="why-grid">{[["01", "Save hundreds of hours", "Give your team time back for the work only humans can do."], ["02", "Increase revenue", "Respond to opportunity at the speed buyers expect."], ["03", "Reduce costs", "Replace capacity constraints with intelligent, consistent execution."], ["04", "24/7 AI employees", "Keep the business moving beyond the limits of the workday."], ["05", "Custom built", "No off-the-shelf workflows forced onto your business."], ["06", "Scales with you", "A technical foundation that earns its place as you grow."]].map(([n,t,c]) => <Reveal key={n}><article className="why-card"><span>{n}</span><h3>{t}</h3><p>{c}</p></article></Reveal>)}</div></section>
    <section id="process" className="process"><SectionTitle eyebrow="HOW WE WORK" title={<>From friction to <em>flow.</em></>} copy="A focused, transparent process that keeps the business outcome in sight."/><div className="timeline">{["Discovery call", "Business analysis", "AI solution design", "Development", "Testing", "Deployment", "Ongoing support"].map((x,i) => <Reveal key={x}><div className="step"><span>0{i+1}</span><b>{x}</b>{i < 6 && <i/>}</div></Reveal>)}</div></section>
    <section id="founder" className="founder"><Reveal className="portrait"><div className="portrait-placeholder"><span>SD</span><p>SHIVAM DHOKANE<br/><small>FOUNDER / AI ARCHITECT</small></p></div></Reveal><Reveal className="founder-copy"><p className="eyebrow">MEET THE FOUNDER</p><h2>Built by a systems thinker<br/>with a bias for <em>action.</em></h2><p>Hi, I’m Shivam Dhokane. I build intelligent automation systems that help ambitious businesses save time, reduce costs, and grow faster.</p><p>From voice AI and LLM applications to CRM integrations and custom agents, my goal is simple: replace repetitive work with intelligence that operates 24/7.</p><div className="stats">{[["50+", "Projects completed"], ["100+", "Automations built"], ["10k+", "Hours returned"]].map(([n,l]) => <div key={l}><b>{n}</b><span>{l}</span></div>)}</div></Reveal></section>
    <section className="testimonials"><SectionTitle eyebrow="CLIENT PERSPECTIVE" title={<>The outcome is<br/><em>the only metric.</em></>} /><div className="quote-grid">{[["“We stopped chasing admin and started chasing growth. The lead system paid for itself in the first month.”", "Maya Chen", "Managing Director, Aster & Co."], ["“It feels less like software and more like adding a sharp, tireless operator to the team.”", "James Walker", "Founder, Brightline"], ["“NEXUS understood the business problem before proposing technology. That changed everything.”", "Sofia Ramirez", "COO, Verity Health"]].map(([q,n,r]) => <Reveal key={n}><blockquote><div>★★★★★</div><p>{q}</p><footer><span>{n}</span>{r}</footer></blockquote></Reveal>)}</div></section>
    <section className="faq"><SectionTitle eyebrow="FREQUENTLY ASKED" title={<>Good questions.<br/><em>Clear answers.</em></>} /><div className="accordion">{faqs.map(([q,a],i) => <div className={open===i ? "faq-item open" : "faq-item"} key={q}><button onClick={() => setOpen(open===i ? null:i)} aria-expanded={open===i}>{q}<ChevronDown size={19}/></button>{open===i && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }}>{a}</motion.p>}</div>)}</div></section>
    <section id="contact" className="contact"><Reveal><div className="contact-card"><div><p className="eyebrow">MAKE THE FIRST MOVE</p><h2>Your next best<br/>employee is <em>AI.</em></h2><p>Bring us the bottleneck. We’ll bring the system that clears it.</p><div className="contact-meta"><Mail size={16}/> hello@nexusautomation.ai</div></div><form onSubmit={e => e.preventDefault()}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Company<input placeholder="Company name"/></label><label>Phone<input type="tel" placeholder="+1 000 000 0000"/></label><label className="full">What would you like to automate?<textarea placeholder="Tell us about the bottleneck..." rows={3}/></label><button className="button button-primary full">Book consultation <ArrowRight size={17}/></button></form></div></Reveal></section>
    <footer className="site-footer"><a className="brand" href="#top"><span>N</span>NEXUS</a><p>Intelligent systems for businesses<br/>that intend to lead.</p><div className="footer-links"><a href="#services">Capabilities</a><a href="#work">Work</a><a href="#contact">Contact</a></div><div className="socials"><a aria-label="LinkedIn" href="#"><Linkedin size={18}/></a><a aria-label="GitHub" href="#"><Github size={18}/></a><a aria-label="Instagram" href="#"><Instagram size={18}/></a></div><small>© 2026 NEXUS Automation. All rights reserved.</small></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "ProfessionalService", name: "NEXUS AI Automation", description: "Custom AI agents and automation systems for businesses." }) }} />
  </main>;
}
